### ISSUE TITLE
[FEATURE] Update Dependabot Workflow

### ISSUE THREAD

**Issue by Anmol-Baranwal** [UniKonf/Vibey#503]
### Detailed description

> Current One:

```yml
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
```

Firstly, it should have a proper commit prefix according to conventions, such as `chore(deps)`. Additionally, it lacks a label, which could be helpful for someone looking at the PR, like `📦 dependencies`.

Like this: (looks clean and according to conventions)
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/5f7ae417-b0d8-44bc-89e0-0ba02621979e)

### Context

I will add the changes with detailed instructions.

> I will do this contribution under GSSoC'23. So, please assign me and I will make a PR.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
